[project]
name = "apdl_trace"
version = "0.1.0"
description = "APDLの理解を助けるツール"
readme = "README.md"
requires-python = ">=3.11"
# license = { text = "MIT" }
authors = [
  { name = "heppocogne", email = "83043568+heppocogne@users.noreply.github.com" },
]
keywords = []
classifiers = [
  # "Development Status :: 2 - Pre-Alpha",
  "Development Status :: 3 - Alpha",
  # "Development Status :: 4 - Beta",
  # "Development Status :: 5 - Production/Stable",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  # "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Scientific/Engineering",
]
# 標準ライブラリのみの予定
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest>=9.0.0",
    "pytest-cov>=7.0.0",
    "ruff>=0.16.0",
]

[project.urls]
# Homepage = "https://github.com/heppocogne/apdl_trace"

[project.scripts]
apdl_trace = "apdl_trace.main:main"

[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
apdl_trace = ["data/*.json"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
markers = []
